### ISSUE TITLE
Question: UX around Bundle's cycling between Unpacking phase and the UnpackFailed condition

### ISSUE THREAD

**Issue by timflannagan** [joelanford/kuberpak#2]
Note: this isn't an issue per-se, and more-or-less the behavior was something that I noticed poking around the current repository setup locally.

I'm trying to wrap my head around whether it makes sense to continuously reconcile Bundles that are failing to be unpacked (e.g. transient issues, container image doesn't match expected input, underlying pod fails to unpack contents, etc.) and the Bunde's status cycles between an empty status with `phase: Unpacked`, and a populated status:

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-12-12T22:28:55Z"
    message: unpack pod failed
    reason: UnpackFailed
    status: "False"
    type: Unpacked
  observedGeneration: 2
  phase: Unpacking
```

Would it make sense to delineate between unpacking errors that we identify as scenarios that should be requeued immediatley, vs. issues that we have a decent idea won't be solved (e.g. a bad container image)? It seems like the obvious solutions are having different requeue behaviors based on custom errors that get returned from the `unpacker.Unpack` method, or having a validation layer that sits between the process of fetching the bundle from the caching layer, and the unpacking layer. Any idea on whether attempting to delineate between some of these edge cases would lead towards violating any declarative behaviors?
